### ISSUE TITLE
Java Play Framework 2.2.3

### ISSUE THREAD

**Issue by umbreak** [julienrf/play-jsonp-filter#3]
Using `WithFilters` with Java in version 2.2.x is not really possible. According to [this answer in StackOverflow](http://stackoverflow.com/questions/19307850/writing-custom-filters-for-play-2-2-in-java) is possible to do as follows in the `Global.java`:

```
@Override
public <T extends EssentialFilter> Class<T>[] filters() {
    return new Class[] {Jsonp.class};
} 
```

But it throws an exception when running the application:
java.lang.InstantiationException: julienrf.play.jsonp.Jsonp
     java.lang.Class.newInstance(Unknown Source)
     play.core.j.JavaGlobalSettingsAdapter$$anonfun$doFilter$1.apply(JavaGlobalSettingsAdapter.scala:57) ...

There is some way to run this module with Java?

**Comment by julienrf** [comment]
It should work if you use the `JsonpJava` class instead of `Jsonp`:

``` java
return new Class[]{julienrf.play.jsonp.JsonpJava.class};
```

**Comment by umbreak** [comment]
I am afraid `JsonJava` is only available for the version 1.2 and I am still using 2.2.3. In your documentation it says "use 1.1 for play 2.2.x and 1.2 for play 2.3.x".

**Comment by julienrf** [comment]
Sorry, I didn’t pay attention to that. v1.1 had no built-in Java support, but you can define the following class in your project:

``` java
package julienrf.play.jsonp;

import play.api.mvc.Codec;
import play.api.libs.concurrent.Execution;

class JsonpJava extends Jsonp {
  public JsonpJava() {
    super("callback", Codec.utf_8(), Execution.defaultContext());
  }
}
```

**Comment by umbreak** [comment]
It worked. Thanks!

**Comment by julienrf** [comment]
You’re welcome :)
